<?php
/**
 * @var Attributes $block
 */
/** @var $escaper Escaper */

use BPerevyazko\ProductLabel\ViewModel\ProductData;
use Magento\Catalog\Block\Product\View\Attributes;
use Magento\Framework\Escaper;

?>
<?php
/** @var ProductData $viewModel */
$viewModel = $block->getData('view_model');
$jsonData = $viewModel->getProductLabels($block->getProduct());
?>
<script type="text/x-magento-init">
    {
        "*": {
            "productLabel": <?=/* @noEscape */ $jsonData ?>
        }
    }

</script>
