<?php
/**
 * @var Attributes $block
 */
/** @var $escaper \Magento\Framework\Escaper */

use BPerevyazko\ProductLabel\ViewModel\ProductData;
use Magento\Catalog\Block\Product\View\Attributes;
?>
<?php
/** @var ProductData $viewModel */
$viewModel = $block->getData('view_model');
$jsonData = $viewModel->getProductLabels($block->getProduct());
?>
<div class="product-labels" data-mage-init='{"productLabel":<?= /* @noEscape */ $jsonData ?>}'>

</div>
